num_seq=$(grep ">" "$1" | wc -l)
total_len=$(echo "$lengths" | awk '{s+=$1} END {print s}')
max_len=$(echo "$lengths" | awk 'BEGIN{m=0} {if($1>m)m=$1} END{print m}')
min_len=$(echo "$lengths" | awk 'NR==1{m=$1} {if($1<m)m=$1} END{print m}')
_count=$(grep -v "^>" "$file" | tr -cd 'GCgc' | wc -c)